### PR TITLE
Water stuff

### PR DESCRIPTION
**Pull request by konstanty-kordas**

### CODE REVIEW

**Comment by AN0DA** [comment]
That's why smaller branches are more convenient. Resolving conflicts will be fun!

**Comment by konstanty-kordas** [comment]
vcprojx pliki sa zle zrobione ale to mozna potem naprawic

**Comment by AN0DA** [comment]
Thanks for fixing conflicts, but whole think doesn't build. Please fix

**Comment by Chl3bak05** [comment]
should it show blank screen?

**Comment by konstanty-kordas** [comment]
> 
> 
> should it show blank screen?

fixed

**Pull request merged**
